//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.30 at 04:02:43 PM CST 
//


package uia.sketch.model.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uia.sketch.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SketchBook_QNAME = new QName("http://sketch.uia/model/xml", "sketchBook");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uia.sketch.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SketchBookType }
     * 
     */
    public SketchBookType createSketchBookType() {
        return new SketchBookType();
    }

    /**
     * Create an instance of {@link PhotoListType }
     * 
     */
    public PhotoListType createPhotoListType() {
        return new PhotoListType();
    }

    /**
     * Create an instance of {@link GridListType }
     * 
     */
    public GridListType createGridListType() {
        return new GridListType();
    }

    /**
     * Create an instance of {@link PhotoType }
     * 
     */
    public PhotoType createPhotoType() {
        return new PhotoType();
    }

    /**
     * Create an instance of {@link GridType }
     * 
     */
    public GridType createGridType() {
        return new GridType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SketchBookType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sketch.uia/model/xml", name = "sketchBook")
    public JAXBElement<SketchBookType> createSketchBook(SketchBookType value) {
        return new JAXBElement<SketchBookType>(_SketchBook_QNAME, SketchBookType.class, null, value);
    }

}
